server.port: 9091

spring.application.name: loki-gateway

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: provider
          uri: http://localhost:8088
          predicates:
            - Path=/api/provider/**
          filters:
            - StripPrefix=2
